/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `/articles/details`; params?: Router.UnknownInputParams; } | { pathname: `/assets/details`; params?: Router.UnknownInputParams; } | { pathname: `/assets`; params?: Router.UnknownInputParams; } | { pathname: `/assets/items`; params?: Router.UnknownInputParams; } | { pathname: `/users/about`; params?: Router.UnknownInputParams; } | { pathname: `/users/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/users/profile`; params?: Router.UnknownInputParams; } | { pathname: `/users/question`; params?: Router.UnknownInputParams; } | { pathname: `/users/setting`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownOutputParams; } | { pathname: `/articles/details`; params?: Router.UnknownOutputParams; } | { pathname: `/assets/details`; params?: Router.UnknownOutputParams; } | { pathname: `/assets`; params?: Router.UnknownOutputParams; } | { pathname: `/assets/items`; params?: Router.UnknownOutputParams; } | { pathname: `/users/about`; params?: Router.UnknownOutputParams; } | { pathname: `/users/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/users/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/users/question`; params?: Router.UnknownOutputParams; } | { pathname: `/users/setting`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/users${`?${string}` | `#${string}` | ''}` | `/users${`?${string}` | `#${string}` | ''}` | `/articles/details${`?${string}` | `#${string}` | ''}` | `/assets/details${`?${string}` | `#${string}` | ''}` | `/assets${`?${string}` | `#${string}` | ''}` | `/assets/items${`?${string}` | `#${string}` | ''}` | `/users/about${`?${string}` | `#${string}` | ''}` | `/users/privacy${`?${string}` | `#${string}` | ''}` | `/users/profile${`?${string}` | `#${string}` | ''}` | `/users/question${`?${string}` | `#${string}` | ''}` | `/users/setting${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/users` | `/users`; params?: Router.UnknownInputParams; } | { pathname: `/articles/details`; params?: Router.UnknownInputParams; } | { pathname: `/assets/details`; params?: Router.UnknownInputParams; } | { pathname: `/assets`; params?: Router.UnknownInputParams; } | { pathname: `/assets/items`; params?: Router.UnknownInputParams; } | { pathname: `/users/about`; params?: Router.UnknownInputParams; } | { pathname: `/users/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/users/profile`; params?: Router.UnknownInputParams; } | { pathname: `/users/question`; params?: Router.UnknownInputParams; } | { pathname: `/users/setting`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
